
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjfdxrgrvolpzaemcihn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZmR4cmdydm9scHphZW1jaWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTIwOTQsImV4cCI6MjA2MDUyODA5NH0.UJ2OJs0MZcG0LdRT1lAKknUxWBNq0OaNjeiS0uiw3ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define RPC function signatures for TypeScript
export type SupabaseRpcFunctions = {
  ensure_series_table: {
    Args: Record<string, never>;
    Returns: void;
  };
  save_series: {
    Args: {
      p_exercicio_id: string;
      p_numero_serie: number;
      p_peso: number;
      p_repeticoes: number;
      p_concluida: boolean;
    };
    Returns: void;
  };
  get_series_by_exercise: {
    Args: {
      exercise_id: string;
    };
    Returns: {
      id: string;
      exercicio_usuario_id: string;
      numero_serie: number;
      peso: number;
      repeticoes: number;
      concluida: boolean;
      created_at: string;
      updated_at: string;
    }[];
  };
};

export const supabase = createClient<Database, SupabaseRpcFunctions>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
