// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjfdxrgrvolpzaemcihn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZmR4cmdydm9scHphZW1jaWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTIwOTQsImV4cCI6MjA2MDUyODA5NH0.UJ2OJs0MZcG0LdRT1lAKknUxWBNq0OaNjeiS0uiw3ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);